INSERT INTO Anbefaling (SkismoringID, SnoforholdID, NivaID, LoypeforholdID) VALUES
(1, 1, 1, 1),    -- Swix VR30 anbefales for nybegynnere i Lysløypa Nord (Tørr snø -15°C)
(2, 1, 2, 2),    -- Swix VR40 anbefales for erfarne i Fjellrunden Vest (Tørr snø -15°C)
(3, 2, 2, 3),    -- Swix VR50 anbefales for erfarne i Elveløypa Øst (Tørr snø -5°C)
(4, 3, 2, 4),    -- Swix KX20 anbefales for erfarne i Skogstrase A (Våt snø 1°C)
(5, 4, 1, 5),    -- Swix KX40S anbefales for nybegynnere i Sprintløype (Is/snø blanding -3°C)
(6, 4, 1, 6),    -- Swix KX75 anbefales for nybegynnere i Kunstsnøbanen (Is/snø blanding -3°C)
(7, 3, 3, 7),    -- Swix CH10 anbefales for konkurranseløpere i Toppturløypa (Våt snø 1°C)
(8, 5, 2, 8),    -- Swix CH6 anbefales for erfarne i Vindmyrunden (Grovkornet snø 3°C)
(9, 6, 3, 9),    -- Swix HS8 anbefales for konkurranseløpere i Barnebakken (Kunstsnø -8°C)
(10, 2, 1, 10),  -- Toko Red anbefales for nybegynnere i Grusbakken (Tørr snø -5°C)
(11, 1, 2, 11),  -- Rex Blue anbefales for erfarne i Mildskogen (Tørr snø -15°C)
(12, 4, 1, 12),  -- Rode Rossa anbefales for nybegynnere i Søndagsløypa (Is/snø blanding -3°C)
(13, 4, 1, 13),  -- Swix Quick Wax anbefales for nybegynnere i Sørhellinga (Is/snø blanding -3°C)
(14, 6, 3, 14),  -- Vauhti Pure One anbefales for konkurranseløpere i Isbakken (Kunstsnø -8°C)

-- Oppdatert underveis
(5, 4, 1, 13),   -- Swix KX40S anbefales for nybegynnere i Sørhellinga (Is/snø blanding -3°C)
(6, 4, 1, 6),    -- Swix KX75 anbefales for nybegynnere i Kunstsnøbanen (Is/snø blanding -3°C)
(13, 4, 1, 13),  -- Swix Quick Wax anbefales for nybegynnere i Sørhellinga (Is/snø blanding -3°C)
(7, 3, 3, 3),    -- Swix CH10 anbefales for konkurranseløpere i Elveløypa Øst (Våt snø 1°C)
(14, 6, 3, 14),  -- Vauhti Pure One anbefales for konkurranseløpere i Isbakken (Kunstsnø -8°C)
(11, 1, 2, 11),  -- Rex Blue anbefales for erfarne i Mildskogen (Tørr snø -15°C)
(2, 1, 2, 2),    -- Swix VR40 anbefales for erfarne i Fjellrunden Vest (Tørr snø -15°C)
(3, 2, 2, 3),    -- Swix VR50 anbefales for erfarne i Elveløypa Øst (Tørr snø -5°C)
(4, 3, 2, 4),    -- Swix KX20 anbefales for erfarne i Skogstrase A (Våt snø 1°C)
(8, 5, 2, 12),   -- Swix CH6 anbefales for erfarne i Vindmyrunden (Grovkornet snø 3°C)
(12, 4, 1, 12),  -- Rode Rossa anbefales for nybegynnere i Søndagsløypa (Is/snø blanding -3°C)
(9, 6, 3, 9);    -- Swix HS8 anbefales for konkurranseløpere i Barnebakken (Kunstsnø -8°C)
